import type { SquareType } from "./square";

export type PieceType = 'wp' | 'wr' | 'wn' | 'wb' | 'wq' | 'wk' | 'bp' | 'br' | 'bn' | 'bb' | 'bq' | 'bk' | null;

export type GameType = 'game' | 'freeplay' | 'puzzle' | 'sandbox';

export type BoardType = {
    state: GameType,
    orientation: 'w' | 'b',
    positions: SquareType[],
    winner?: 'w' | 'b' | 'd',
    lastMove?: string,
    turn?: 'w' | 'b',
    check?: 'w' | 'b',
    isMate?: boolean,
}

export const defaultBoard: BoardType = {
    state: 'sandbox',
    orientation: 'w',
    positions: [
        { square: 'a8', piece: 'br' },
        { square: 'b8', piece: 'bn' },
        { square: 'c8', piece: 'bb' },
        { square: 'd8', piece: 'bq' },
        { square: 'e8', piece: 'bk' },
        { square: 'f8', piece: 'bb' },
        { square: 'g8', piece: 'bn' },
        { square: 'h8', piece: 'br' },
        { square: 'a7', piece: 'bp' },
        { square: 'b7', piece: 'bp' },
        { square: 'c7', piece: 'bp' },
        { square: 'd7', piece: 'bp' },
        { square: 'e7', piece: 'bp' },
        { square: 'f7', piece: 'bp' },
        { square: 'g7', piece: 'bp' },
        { square: 'h7', piece: 'bp' },
        { square: 'a6', piece: null },
        { square: 'b6', piece: null },
        { square: 'c6', piece: null },
        { square: 'd6', piece: null },
        { square: 'e6', piece: null },
        { square: 'f6', piece: null },
        { square: 'g6', piece: null },
        { square: 'h6', piece: null },
        { square: 'a5', piece: null },
        { square: 'b5', piece: null },
        { square: 'c5', piece: null },
        { square: 'd5', piece: null },
        { square: 'e5', piece: null },
        { square: 'f5', piece: null },
        { square: 'g5', piece: null },
        { square: 'h5', piece: null },
        { square: 'a4', piece: null },
        { square: 'b4', piece: null },
        { square: 'c4', piece: null },
        { square: 'd4', piece: null },
        { square: 'e4', piece: null },
        { square: 'f4', piece: null },
        { square: 'g4', piece: null },
        { square: 'h4', piece: null },
        { square: 'a3', piece: null },
        { square: 'b3', piece: null },
        { square: 'c3', piece: null },
        { square: 'd3', piece: null },
        { square: 'e3', piece: null },
        { square: 'f3', piece: null },
        { square: 'g3', piece: null },
        { square: 'h3', piece: null },
        { square: 'a2', piece: 'wp' },
        { square: 'b2', piece: 'wp' },
        { square: 'c2', piece: 'wp' },
        { square: 'd2', piece: 'wp' },
        { square: 'e2', piece: 'wp' },
        { square: 'f2', piece: 'wp' },
        { square: 'g2', piece: 'wp' },
        { square: 'h2', piece: 'wp' },
        { square: 'a1', piece: 'wr' },
        { square: 'b1', piece: 'wn' },
        { square: 'c1', piece: 'wb' },
        { square: 'd1', piece: 'wq' },
        { square: 'e1', piece: 'wk' },
        { square: 'f1', piece: 'wb' },
        { square: 'g1', piece: 'wn' },
        { square: 'h1', piece: 'wr' },
    ],
}